/*
 * © 2008 3kraft
 * $Id: PreferencesDialog.java,v 1.13 2010-12-03 18:10:03 illetsch Exp $
 */
package com.dreikraft.axbo.gui;

import com.dreikraft.events.ApplicationEventDispatcher;
import com.dreikraft.axbo.controller.PreferencesController;
import com.dreikraft.axbo.events.PrefsClose;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 * $Id: PreferencesDialog.java,v 1.13 2010-12-03 18:10:03 illetsch Exp $
 * 
 * @author 3kraft - $Author: illetsch $
 * @version $Revision: 1.13 $
 */
public class PreferencesDialog extends javax.swing.JDialog
{
  private PreferencesController ctrl;

  public PreferencesDialog(java.awt.Frame parent, boolean modal,
      final PreferencesController ctrl)
  {
    super(parent, modal);
    this.ctrl = ctrl;
    setResizable(false);
    initComponents();
  }

  /** Creates new form PreferencesDialog */
  public PreferencesDialog(java.awt.Frame parent, boolean modal)
  {
    this(parent, modal, null);
  }

  public void setController(PreferencesController ctrl)
  {
    this.ctrl = ctrl;
  }

  public void initComPortCB(final List<String> items, final String sel)
  {
    final ComboBoxModel<String> model = new DefaultComboBoxModel<String>(
        items.toArray(new String[0]));
    this.comPortCB.setModel(model);
    this.comPortCB.setSelectedItem(sel);
  }

  public void initLanguageCB(final List<String> items, String sel)
  {
    final ComboBoxModel<String> model = new DefaultComboBoxModel<String>(
        items.toArray(new String[0]));
    this.languageCB.setModel(model);
    this.languageCB.setSelectedItem(sel);
  }

  public String getComPortValue()
  {
    return (String) this.comPortCB.getSelectedItem();
  }

  public int getLanguageIndex()
  {
    return this.languageCB.getSelectedIndex();
  }

  public void setSelectedComPort(String comPortName)
  {
    this.comPortCB.setSelectedItem(comPortName);
  }

  public String getSensor1Name()
  {
    return sensor1NameTextField.getText();
  }

  public void setSensor1Name(String name)
  {
    sensor1NameTextField.setText(name);
  }

  public String getSensor2Name()
  {
    return sensor2NameTextField.getText();
  }

  public void setSensor2Name(String name)
  {
    sensor2NameTextField.setText(name);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    PreferencesPanel = new javax.swing.JPanel();
    comPortLabel = new javax.swing.JLabel();
    languageLabel = new javax.swing.JLabel();
    languageCB = new javax.swing.JComboBox<String>();
    saveButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    comPortCB = new javax.swing.JComboBox<String>();
    sensor1NameLabel = new javax.swing.JLabel();
    sensor2NameLabel = new javax.swing.JLabel();
    sensor1NameTextField = new javax.swing.JTextField();
    sensor2NameTextField = new javax.swing.JTextField();
    restartLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/default"); // NOI18N
    setTitle(bundle.getString("preferences.frame.title")); // NOI18N
    setAlwaysOnTop(true);
    setModal(true);
    setName("preferencesDialog"); // NOI18N
    setResizable(false);

    PreferencesPanel.setFocusable(false);
    PreferencesPanel.setMaximumSize(null);

    comPortLabel.setLabelFor(comPortCB);
    comPortLabel.setText(bundle.getString("preferences.label.comPort")); // NOI18N

    languageLabel.setLabelFor(languageCB);
    languageLabel.setText(bundle.getString("preferences.label.language")); // NOI18N

    saveButton.setText(bundle.getString("preferences.button.save")); // NOI18N
    saveButton.putClientProperty("JButton.buttonType", "textured");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });

    cancelButton.setText(bundle.getString("preferences.button.cancel")); // NOI18N
    cancelButton.setMaximumSize(null);
    cancelButton.setMinimumSize(null);
    cancelButton.setPreferredSize(null);
    cancelButton.putClientProperty("JButton.buttonType", "textured");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });

    sensor1NameLabel.setText(bundle.getString("label.sensor1Name")); // NOI18N

    sensor2NameLabel.setText(bundle.getString("label.sensor2Name")); // NOI18N

    restartLabel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
    restartLabel.setForeground(new java.awt.Color(255, 0, 0));
    restartLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    restartLabel.setText(bundle.getString("preference.label.restart")); // NOI18N

    org.jdesktop.layout.GroupLayout PreferencesPanelLayout = new org.jdesktop.layout.GroupLayout(PreferencesPanel);
    PreferencesPanel.setLayout(PreferencesPanelLayout);
    PreferencesPanelLayout.setHorizontalGroup(
      PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(PreferencesPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, PreferencesPanelLayout.createSequentialGroup()
            .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(saveButton))
          .add(PreferencesPanelLayout.createSequentialGroup()
            .add(13, 13, 13)
            .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
              .add(sensor2NameLabel)
              .add(sensor1NameLabel)
              .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(languageLabel)
                .add(comPortLabel)))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
              .add(PreferencesPanelLayout.createSequentialGroup()
                .add(languageCB, 0, 216, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(restartLabel))
              .add(org.jdesktop.layout.GroupLayout.LEADING, comPortCB, 0, 280, Short.MAX_VALUE)
              .add(org.jdesktop.layout.GroupLayout.LEADING, sensor1NameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
              .add(org.jdesktop.layout.GroupLayout.LEADING, sensor2NameTextField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))))
        .addContainerGap())
    );
    PreferencesPanelLayout.setVerticalGroup(
      PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(PreferencesPanelLayout.createSequentialGroup()
        .addContainerGap()
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(restartLabel)
          .add(languageCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(languageLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(comPortCB, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(comPortLabel))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(sensor1NameLabel)
          .add(sensor1NameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(sensor2NameLabel)
          .add(sensor2NameTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(PreferencesPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(saveButton)
          .add(cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(28, Short.MAX_VALUE))
    );

    getContentPane().add(PreferencesPanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    ApplicationEventDispatcher.getInstance().dispatchGUIEvent(new PrefsClose(
        this, false));
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_saveButtonActionPerformed
  {//GEN-HEADEREND:event_saveButtonActionPerformed
    ApplicationEventDispatcher.getInstance().dispatchGUIEvent(new PrefsClose(
        this, true));
  }//GEN-LAST:event_saveButtonActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel PreferencesPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JComboBox<String> comPortCB;
  private javax.swing.JLabel comPortLabel;
  private javax.swing.JComboBox<String> languageCB;
  private javax.swing.JLabel languageLabel;
  private javax.swing.JLabel restartLabel;
  private javax.swing.JButton saveButton;
  private javax.swing.JLabel sensor1NameLabel;
  private javax.swing.JTextField sensor1NameTextField;
  private javax.swing.JLabel sensor2NameLabel;
  private javax.swing.JTextField sensor2NameTextField;
  // End of variables declaration//GEN-END:variables
}
