/*
 * © 2008 3kraft
 * $Id: SoundPackageFrame.java,v 1.11 2010-11-30 14:45:34 illetsch Exp $
 */
package com.dreikraft.axbo.gui;

import com.dreikraft.axbo.Axbo;
import com.dreikraft.axbo.controller.SoundPackageFrameController;
import com.dreikraft.axbo.model.SoundsTableModel;
import com.dreikraft.axbo.sound.Sound;
import com.dreikraft.swing.IconCellRenderer;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * $Id: SoundPackageFrame.java,v 1.11 2010-11-30 14:45:34 illetsch Exp $
 * 
 * @author 3kraft - $Author: illetsch $
 * @version $Revision: 1.11 $
 */
public class SoundPackageFrame extends javax.swing.JPanel
{
  public final Log log = LogFactory.getLog(SoundPackageFrame.class);
  private SoundPackageFrameController ctrl;

  /** Creates new form SoundPackageFrame */
  public SoundPackageFrame(SoundPackageFrameController ctrl)
  {
    this.ctrl = ctrl;

    // small title
    putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);

    initComponents();

    lblPkgNameVal.setText(ctrl.getSoundPkg().getName());
    lblSNVal.setText(ctrl.getSoundPkg().getSerialNumber());
    lblCreatorVal.setText(ctrl.getSoundPkg().getCreator());
    if (ctrl.getSoundPkg().getCreationDate() != null)
    {
      lblCreationDateVal.setText(SimpleDateFormat.getDateInstance(
          SimpleDateFormat.SHORT).format(ctrl.getSoundPkg().getCreationDate()));
    }
    tblSounds.setModel(new SoundsTableModel(ctrl.getSoundPkg().
        getSounds()));
    tblSounds.getColumnModel().getColumn(0).setCellRenderer(
        new IconCellRenderer(Axbo.SOUND_PLAYING_ICON, "x"));
    tblSounds.getColumnModel().getColumn(0).setPreferredWidth(20);
    tblSounds.getColumnModel().getColumn(0).setMaxWidth(20);
    tblSounds.getColumnModel().getColumn(0).setResizable(false);
    tblSounds.getColumnModel().getColumn(1).setPreferredWidth(25);
    tblSounds.getColumnModel().getColumn(1).setMaxWidth(25);
    tblSounds.getColumnModel().getColumn(1).setResizable(false);

    // initialize the view
    //this.setTitle(ctrl.getSoundPkg().getName());
    this.setVisible(true);
    tblSounds.selectAll();
  }

  public void playbackStarted(final boolean enableSkip)
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        btnPlaySound.setEnabled(false);
        btnSkipBack.setEnabled(enableSkip);
        btnSkipForward.setEnabled(enableSkip);
        btnStopSound.setEnabled(true);
      }
    });
  }

  public void playbackStopped()
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        btnPlaySound.setEnabled(true);
        btnSkipBack.setEnabled(false);
        btnSkipForward.setEnabled(false);
        btnStopSound.setEnabled(false);
      }
    });
  }

  public void soundStarted(final Sound sound)
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        tblSounds.repaint();
      }
    });
  }

  public void soundStopped(final Sound sound)
  {
    SwingUtilities.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        tblSounds.repaint();
      }
    });
  }

  public void bringToFront()
  {
    try
    {
      //setSelected(true);
      //setMaximum(true);
    }
    catch (Exception ex)
    {
      log.error(ex.getMessage(), ex);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlMain = new javax.swing.JPanel();
    pnlNorth = new javax.swing.JPanel();
    tlbSounds = new javax.swing.JToolBar();
    btnSkipBack = new javax.swing.JButton();
    btnPlaySound = new javax.swing.JButton();
    btnStopSound = new javax.swing.JButton();
    btnSkipForward = new javax.swing.JButton();
    btnUpload = new javax.swing.JButton();
    pnlPackageInfo = new javax.swing.JPanel();
    lblPkgName = new javax.swing.JLabel();
    lblSN = new javax.swing.JLabel();
    lblCreationDate = new javax.swing.JLabel();
    lblCreator = new javax.swing.JLabel();
    lblPkgNameVal = new javax.swing.JLabel();
    lblSNVal = new javax.swing.JLabel();
    lblCreationDateVal = new javax.swing.JLabel();
    lblCreatorVal = new javax.swing.JLabel();
    spnSounds = new javax.swing.JScrollPane();
    tblSounds = new javax.swing.JTable();

    setLayout(new java.awt.BorderLayout());

    pnlMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
    pnlMain.setLayout(new java.awt.BorderLayout());

    pnlNorth.setLayout(new java.awt.BorderLayout());

    tlbSounds.setFloatable(false);
    tlbSounds.setRollover(true);
    tlbSounds.setFocusable(false);
    tlbSounds.setMaximumSize(new java.awt.Dimension(100000, 32));
    tlbSounds.setMinimumSize(new java.awt.Dimension(24, 32));
    tlbSounds.setPreferredSize(new java.awt.Dimension(100, 32));

    btnSkipBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/control_start_blue.png"))); // NOI18N
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/default"); // NOI18N
    btnSkipBack.setToolTipText(bundle.getString("btnSkipBack.tooltip")); // NOI18N
    btnSkipBack.setEnabled(false);
    btnSkipBack.setFocusable(false);
    btnSkipBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSkipBack.setMaximumSize(new java.awt.Dimension(28, 26));
    btnSkipBack.setMinimumSize(new java.awt.Dimension(28, 26));
    btnSkipBack.setPreferredSize(new java.awt.Dimension(28, 26));
    btnSkipBack.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnSkipBack.putClientProperty("JButton.buttonType", "segmentedTextured");
    btnSkipBack.putClientProperty("JButton.segmentPosition", "first");
    btnSkipBack.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSkipBackActionPerformed(evt);
      }
    });
    tlbSounds.add(btnSkipBack);

    btnPlaySound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/control_play_blue.png"))); // NOI18N
    btnPlaySound.setToolTipText(bundle.getString("btnPlaySound.tooltip")); // NOI18N
    btnPlaySound.setFocusable(false);
    btnPlaySound.setMaximumSize(new java.awt.Dimension(28, 26));
    btnPlaySound.setMinimumSize(new java.awt.Dimension(28, 26));
    btnPlaySound.setPreferredSize(new java.awt.Dimension(28, 26));
    btnPlaySound.putClientProperty("JButton.buttonType", "segmentedTextured");
    btnPlaySound.putClientProperty("JButton.segmentPosition", "middle");
    btnPlaySound.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnPlaySoundActionPerformed(evt);
      }
    });
    tlbSounds.add(btnPlaySound);

    btnStopSound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/control_stop_blue.png"))); // NOI18N
    btnStopSound.setToolTipText(bundle.getString("btnStopSound.tooltip")); // NOI18N
    btnStopSound.setEnabled(false);
    btnStopSound.setFocusable(false);
    btnStopSound.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnStopSound.setMaximumSize(new java.awt.Dimension(28, 26));
    btnStopSound.setMinimumSize(new java.awt.Dimension(28, 26));
    btnStopSound.setPreferredSize(new java.awt.Dimension(28, 26));
    btnStopSound.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnStopSound.putClientProperty("JButton.buttonType", "segmentedTextured");
    btnStopSound.putClientProperty("JButton.segmentPosition", "middle");
    btnStopSound.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnStopSoundActionPerformed(evt);
      }
    });
    tlbSounds.add(btnStopSound);

    btnSkipForward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/control_end_blue.png"))); // NOI18N
    btnSkipForward.setToolTipText(bundle.getString("btnSkipForward.tooltip")); // NOI18N
    btnSkipForward.setEnabled(false);
    btnSkipForward.setFocusable(false);
    btnSkipForward.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    btnSkipForward.setMaximumSize(new java.awt.Dimension(28, 26));
    btnSkipForward.setMinimumSize(new java.awt.Dimension(28, 26));
    btnSkipForward.setPreferredSize(new java.awt.Dimension(28, 26));
    btnSkipForward.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    btnSkipForward.putClientProperty("JButton.buttonType", "segmentedTextured");
    btnSkipForward.putClientProperty("JButton.segmentPosition", "last");
    btnSkipForward.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSkipForwardActionPerformed(evt);
      }
    });
    tlbSounds.add(btnSkipForward);

    btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/arrow_up.png"))); // NOI18N
    btnUpload.setText(bundle.getString("btnUpload.text")); // NOI18N
    btnUpload.setToolTipText(bundle.getString("btnUpload.tooltip")); // NOI18N
    btnUpload.setFocusable(false);
    btnUpload.setMaximumSize(new java.awt.Dimension(100, 26));
    btnUpload.setMinimumSize(new java.awt.Dimension(100, 26));
    btnUpload.setMultiClickThreshhold(1000L);
    btnUpload.setPreferredSize(new java.awt.Dimension(100, 26));
    btnUpload.putClientProperty("JButton.buttonType", "textured");
    btnUpload.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnUploadActionPerformed(evt);
      }
    });
    tlbSounds.add(btnUpload);

    pnlNorth.add(tlbSounds, java.awt.BorderLayout.SOUTH);

    lblPkgName.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblPkgName.setText(bundle.getString("lblPkgName.text")); // NOI18N

    lblSN.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblSN.setText(bundle.getString("lblSN.text")); // NOI18N

    lblCreationDate.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
    lblCreationDate.setText(bundle.getString("lblCreationDate")); // NOI18N

    lblCreator.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblCreator.setText(bundle.getString("lblCreator.text")); // NOI18N

    lblPkgNameVal.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblPkgNameVal.setText(" ");

    lblSNVal.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblSNVal.setText(" ");

    lblCreationDateVal.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
    lblCreationDateVal.setText(" ");

    lblCreatorVal.setFont(new java.awt.Font("Lucida Grande", 0, 10));
    lblCreatorVal.setText(" ");

    org.jdesktop.layout.GroupLayout pnlPackageInfoLayout = new org.jdesktop.layout.GroupLayout(pnlPackageInfo);
    pnlPackageInfo.setLayout(pnlPackageInfoLayout);
    pnlPackageInfoLayout.setHorizontalGroup(
      pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(pnlPackageInfoLayout.createSequentialGroup()
        .addContainerGap()
        .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(pnlPackageInfoLayout.createSequentialGroup()
            .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
              .add(lblSN)
              .add(lblPkgName)
              .add(lblCreator))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(lblSNVal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
              .add(lblPkgNameVal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
              .add(org.jdesktop.layout.GroupLayout.TRAILING, lblCreatorVal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)))
          .add(pnlPackageInfoLayout.createSequentialGroup()
            .add(40, 40, 40)
            .add(lblCreationDate)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(lblCreationDateVal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)))
        .addContainerGap())
    );
    pnlPackageInfoLayout.setVerticalGroup(
      pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(pnlPackageInfoLayout.createSequentialGroup()
        .addContainerGap()
        .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(lblPkgName)
          .add(lblPkgNameVal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(lblSN)
          .add(lblSNVal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(lblCreatorVal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(lblCreator))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(pnlPackageInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(lblCreationDateVal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(lblCreationDate))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnlNorth.add(pnlPackageInfo, java.awt.BorderLayout.CENTER);

    pnlMain.add(pnlNorth, java.awt.BorderLayout.NORTH);

    tblSounds.setModel(new SoundsTableModel());
    tblSounds.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    tblSounds.setDoubleBuffered(true);
    tblSounds.setGridColor(new java.awt.Color(240, 240, 240));
    tblSounds.getColumnModel().getColumn(0).setCellRenderer(new IconCellRenderer(Axbo.SOUND_PLAYING_ICON, "x"));
    tblSounds.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tblSoundsMouseClicked(evt);
      }
    });
    spnSounds.setViewportView(tblSounds);

    pnlMain.add(spnSounds, java.awt.BorderLayout.CENTER);

    add(pnlMain, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt)//GEN-FIRST:event_formInternalFrameClosed
  {//GEN-HEADEREND:event_formInternalFrameClosed
    ctrl.stopSound();
  }//GEN-LAST:event_formInternalFrameClosed

  private void btnPlaySoundActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPlaySoundActionPerformed
  {//GEN-HEADEREND:event_btnPlaySoundActionPerformed
    int[] rows = tblSounds.getSelectedRows();
    List<Sound> sounds = new ArrayList<Sound>();
    if (rows.length == 0)
    {
      sounds = ((SoundsTableModel) tblSounds.getModel()).getSounds();
    }
    else
    {
      for (int row : rows)
      {
        sounds.add(((SoundsTableModel) tblSounds.getModel()).getSoundAt(row));
      }
    }
    ctrl.playSound(sounds);
  }//GEN-LAST:event_btnPlaySoundActionPerformed

  private void btnStopSoundActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStopSoundActionPerformed
  {//GEN-HEADEREND:event_btnStopSoundActionPerformed
    ctrl.stopSound();
}//GEN-LAST:event_btnStopSoundActionPerformed

  private void btnSkipForwardActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSkipForwardActionPerformed
  {//GEN-HEADEREND:event_btnSkipForwardActionPerformed
    ctrl.skipForward();
}//GEN-LAST:event_btnSkipForwardActionPerformed

  private void btnSkipBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSkipBackActionPerformed
  {//GEN-HEADEREND:event_btnSkipBackActionPerformed
    ctrl.skipBack();
}//GEN-LAST:event_btnSkipBackActionPerformed

  private void tblSoundsMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tblSoundsMouseClicked
  {//GEN-HEADEREND:event_tblSoundsMouseClicked
    if (evt.getClickCount() == 2)
    {
      List<Sound> sounds = new ArrayList<Sound>();
      sounds.add(((SoundsTableModel) tblSounds.getModel()).getSoundAt(
          tblSounds.getSelectedRow()));
      ctrl.playSound(sounds);
    }
  }//GEN-LAST:event_tblSoundsMouseClicked

  private void btnUploadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUploadActionPerformed
  {//GEN-HEADEREND:event_btnUploadActionPerformed
    ctrl.upload();
}//GEN-LAST:event_btnUploadActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnPlaySound;
  private javax.swing.JButton btnSkipBack;
  private javax.swing.JButton btnSkipForward;
  private javax.swing.JButton btnStopSound;
  private javax.swing.JButton btnUpload;
  private javax.swing.JLabel lblCreationDate;
  private javax.swing.JLabel lblCreationDateVal;
  private javax.swing.JLabel lblCreator;
  private javax.swing.JLabel lblCreatorVal;
  private javax.swing.JLabel lblPkgName;
  private javax.swing.JLabel lblPkgNameVal;
  private javax.swing.JLabel lblSN;
  private javax.swing.JLabel lblSNVal;
  private javax.swing.JPanel pnlMain;
  private javax.swing.JPanel pnlNorth;
  private javax.swing.JPanel pnlPackageInfo;
  private javax.swing.JScrollPane spnSounds;
  private javax.swing.JTable tblSounds;
  private javax.swing.JToolBar tlbSounds;
  // End of variables declaration//GEN-END:variables
}
